# services: 
  # api:
  #   depends_on:
  #     - mongodb
  #   container_name: kraniotest
  #   restart: always
  #   build: .
  #   ports:
  #     - "5000:3000"

  # mongodb:
  #   container_name: mongodb
  #   imagen: mongo
  #   ports:
  #     - "27018:27017"


services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    container_name: kranio_exam_cont
    image: kranio_number
    ports:
      - 4000:3000
      - 3001:9229
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    container_name: mongo
    image : mongo
    ports:
      - 27018:27017
    networks:
      - nesjs-network
    restart: always

networks:
    nesjs-network:
      driver: bridge